<?php
ob_start();
include "connection1.php";
//Login Check

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function getName($n) {
    $characters = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    $randomString = '';

    for ($i = 0; $i < $n; $i++) {
        $index = rand(0, strlen($characters) - 1);
        $randomString .= $characters[$index];
    }

    return $randomString;
}

function email($template,$pc_admin_id,$email,$organization,$fname,$con)
{
	/* Exception class. */
	require 'C:\PHPMailer\src\Exception.php';

	/* The main PHPMailer class. */
	require 'C:\PHPMailer\src\PHPMailer.php';

	/* SMTP class, needed if you want to use SMTP. */
	require 'C:\PHPMailer\src\SMTP.php';
  $pc_admin_id=$_SESSION['admin_loggedin_id'];
  //echo "SELECT * FROM `photo_company_profile` WHERE id=$pc_admin_id";
  $get_pcadmin_profile_query=mysqli_query($con,"SELECT * FROM `photo_company_profile` WHERE pc_admin_id=$pc_admin_id");
  $get_profile=mysqli_fetch_assoc($get_pcadmin_profile_query);
  $pcadmin_email=$get_profile['email'];
  $pcadmin_contact=$get_profile['contact_number'];



	$mail = new PHPMailer(true);
	$mail->isSMTP();
	$mail->Host = $_SESSION['emailHost'];
	$mail->SMTPAuth = true;
	// //paste one generated by Mailtrap
	// //paste one generated by Mailtrap
	$mail->Username =$_SESSION['emailUserID'];
	$mail->Password =$_SESSION['emailPassword'];
	$mail->SMTPSecure = 'tls';
	$mail->Port = $_SESSION['emailPort'];
	//$mail->Port = 465;
	//From email address and name
	$mail->From = $_SESSION['emailUserID'];
	$mail->FromName = "Fotopia";

	$mail->addAddress($email);
 // $mail->addAddress("sidambara.selvan@adrgrp.com");


	//Address to which recipient will reply
	$mail->addReplyTo($_SESSION['emailUserID'], "Reply");

	$mail->isHTML(true);
   
	$mail->Subject = "Invitation to join Fotopia";

  
	$mail->Body = "<html><head><style>.titleCss {font-family: \"Roboto\",Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;color:#0275D8 }.emailCss { width:100%;border:solid 1px #DDD;font-family: \"Roboto\",Helvetica,Arial,sans-serif; } </style></head><table cellpadding=\"5\" class=\"emailCss\"><tr><td align=\"left\"><img src=\"".$_SESSION['project_url']."logo.png\" /></td><td align=\"center\" class=\"titleCss\">INVITATION TO JOIN FOTOPIA</td>
  <td align=\"right\"><img src=\"".$_SESSION['project_url'].$get_profile['logo_image_url']."\" width=\"110\" height=\"80\"/></td>  </tr><tr><td align=\"left\">".$_SESSION['support_team_email']."<br>".$_SESSION['support_team_phone']."</td><td colspan=\"2\" align=\"right\">".strtoupper($get_profile['organization_name'])."<br>".$pcadmin_email."<br>".$pcadmin_contact."</td></tr><tr><td colspan=\"2\"><br><br>";
	//$mail->AltBody = "This is the plain text version of the email content";

 

	$mail->Body.=$template."<br><br>";

$mail->Body .= "<a href='{{project_url}}signup.php'
  target='_blank'>Click here</a> to register with Fotopia application.

  <br><br><span style=\"font-size:10px;font-weight:bold;\">*This is an auto generated email notification from Fotopia. Please do not reply back to this email. For any support please write to support@fotopia.no</span><br><br>
Thanks,<br>
Fotopia Team.";

	$mail->Body=str_replace('{{project_url}}', $_SESSION['project_url'] , $mail->Body);
  $mail->Body=str_replace('{{organization}}', $organization , $mail->Body);
	$mail->Body=str_replace('{{name}}',$fname, $mail->Body);
	$mail->Body.="<br><br></td></tr></table></html>";

    //echo $mail->Body;
    // exit;


	try {
	    $mail->send();
	    echo "Message has been sent successfully";
	} catch (Exception $e) {
		echo $e->getMessage();
	    echo "Mailer Error: " . $mail->ErrorInfo;
	}
}
if(isset($_REQUEST['loginbtn']))
{
	header("location:index.php?failed=1");
}
if(isset($_REQUEST['email']))
{
  $pc_admin_id=$_SESSION['admin_loggedin_id'];
	$get_template_query=mysqli_query($con,"SELECT * FROM `email_template` WHERE template_title='Inviting new clients' and pc_admin_id='$pc_admin_id'");
  $get_template=mysqli_fetch_assoc($get_template_query);
	$template=@$get_template['template_body_text'];
	$email=$_REQUEST['email'];
	$get_organization_query=mysqli_query($con,"select * from admin_users where id=$pc_admin_id");
	$get_organization=mysqli_fetch_assoc($get_organization_query);
	$organization=$get_organization['organization_name'];
	$fname=$get_organization['first_name'];

	email($template,$pc_admin_id,$email,$organization,$fname,$con);
 header('location:client.php?f=1');
}
?>
<?php include "header.php";  ?>
 <div class="">
        <div class="" style="margin-left:00px;height:fit-content;width:100%">
            <div class="row">
			<hr class="space s">
                <div class="col-md-2" style="padding-left:10px;">
	<?php include "sidebar.php"; ?>
  <style>
 /* table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {

  text-align: center;
  padding: 8px;
  color: black;
}

tr:nth-child(even) {
  background-color: #dddddd;
}*/

/*.nav-tabs > li.active > a, .current-active {
    background:#000!important;color:#FFF!important;
    border-radius: 20px 20px 0px 0px;
    opacity: 0.8;


}*/

.mfp-container{

background: none !important;

} 
.realtor-btn{
  float:right;
  margin-top:-6px;
}

/*.current-active
{
 background:#000!important;
 color:#FFF!important;border-bottom-color:#000!important;
}*/
@media only screen and (max-width: 600px) {
td
{
min-width:100px!important;
}
.realtor-btn{
  
  margin-top:-30px !important;
}
.link,.link>i{
 margin-right: 70px;
}
.tab-box
{
margin-left:15px!important;
width:100%!important;
}
}
.nav-tabs > li
{
  margin-left: 0px !important;
}
.nav-tabs > li > a:hover
{
  padding-bottom: 8px;
}
.nav-tabs > li.active > a:hover
{
  padding-bottom: 2px;
}


.nav-tabs > li > a
{
  border-radius: 5px!important;
}

.tab-box .nav-tabs li.active 
{
  padding-top: 6px!important;
    padding-bottom: 6px!important;
    padding-left: 0px!important;
    padding-right: 0px!important;
}
th
{
    background: #aad1d6;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 3px !important;
}

  </style>
<script>
function favourite(realtor_id,pc_admin_id)
{
  if(confirm('Are you sure want to add this realtor to your favourite list?'))
var xhttp= new XMLHttpRequest();
  xhttp.onload = function() {
      window.location.href = "client.php";
    }
  xhttp.open("GET", "client_favourite.php?realtor_id="+realtor_id+"&pc_admin_id="+pc_admin_id, true);
  xhttp.send();
}
function unfavourite(realtor_id,pc_admin_id)
{
  if(confirm('Are you sure want to remove this realtor from your favourite list?'))
var xhttp= new XMLHttpRequest();
  xhttp.onload = function() {
      window.location.href = "client.php?f=1";
    }
  xhttp.open("GET", "client_unfavourite.php?realtor_id="+realtor_id+"&pc_admin_id="+pc_admin_id, true);
  xhttp.send();
}

</script>


			</div>
                <div class="col-md-10">
                  <?php   //echo $_SESSION['project_url'];?>
                   <a href="Realtor_registration.php" class="anima-button circle-button btn-sm btn adr-save realtor-btn"  style="position: relative;top: 30px;z-index: 2;"><i class="fa fa-plus"></i>Add Realtor</a>


						 <a href="#tnc" class="anima-button circle-button btn-sm btn adr-save realtor-btn lightbox link"  style="height:30px;color:#000!important;font-weight:600;float:right;margin-right:10px;position: relative;top: 30px;z-index: 2;"><i class="fa fa-paper-plane"></i><span adr_trans="label_send_invite" style="color:#000!important;font-weight:600">Send Invite</span></a>

<?php if(@isset($_REQUEST["a"])) { ?>
                        <div class="success-box" style="display:block;margin-left:300px;">
                            <div class="text-success">Realtor has been successfully added and an invite has been sent successfully </br></br></div>
                        </div>
						<?php }  ?>

                  <div class="col-md-12" style="margin-left:20px;">

                              <div class="tab-box " data-tab-anima="fade-right" style="">


                                  <ul class="nav nav-tabs" style="">
                                      <li id="click1" class="active current-active"><a href="#" id="label_all_realtor" adr_trans="label_all_realtor">All Realtor</a></li>
                                      <li id="click2"><a href="#" id="label_favourite_realtor" adr_trans="label_favourite_realtor">My Favourite Realtor</a></li>

                                  </ul>
                                  <div class="panel active" style="background-color: white;" id="tab1">
                                    <div class="col-md-12">

																		<form name="realtorSearch" method="post" action="client.php" >
																	  <input type="text" class="form-control form-value" name="filter_realtor" value="<?php echo @$_REQUEST['filter_realtor'];?>" placeholder="Search by Name,City,Organization and hit enter key" onBlur="this.form.submit()" align="center" style="margin-left:25px;height:30px;width:96%"/>
																		</form>
																		</div>
						
                                    <hr class="space s">

									 <div style="width:100%;scrollbar-width: none;overflow-x: scroll;overflow-y:hidden">
               <table align="center" class="table-stripped" style="background:#FFF;color:#000;width:98%">
                                       <tr style="border:solid 2px #aad1d6;">
                                         <th><span adr_trans="label_first_name">Firstname</span></th>
                                         <th><span adr_trans="label_last_name">Lastname</span></th>
										<th><span adr_trans="label_organization">Organization</span></th>
                                         <th><span adr_trans="label_address">Address</span></th>
                                            <th><span adr_trans="label_city">City</span></th>
                                               <th><span adr_trans="label_state">state</span></th>
                                               <th><span adr_trans="label_country">Country</span></th>
                                                  <th><span adr_trans="label_details">Details</span></th>
                                                  <th><span adr_trans="label_add_favourite">Add to favourite</span></td>
                                       </tr>
                                       <?php
                                       $loggedin_id=$_SESSION['admin_loggedin_id'];


$realtor_query="";

if(@$_REQUEST['filter_realtor'])
{
$searchKey=$_REQUEST['filter_realtor'];
$conditions="and (first_name like '%$searchKey%' or last_name like '%$searchKey%' or organization_name like '%$searchKey%' or city like '%$searchKey%')";
$realtor_query=mysqli_query($con,"select * from user_login where email_verified=1 and type_of_user='Realtor' $conditions");
}
else
{
// $realtor_query=mysqli_query($con,"select * from user_login where type_of_user='Realtor' and id not in(select realtor_id from company_favourite_realtor where pc_admin_id='$loggedin_id')");
	$realtor_query=mysqli_query($con,"select * from user_login where email_verified=1 and type_of_user='Realtor'");
}






                       // $realtor_query=mysqli_query($con,"select * from user_login where type_of_user='Realtor' and id not in(select realtor_id from company_favourite_realtor where pc_admin_id='$loggedin_id')");
                                       while($realtor=mysqli_fetch_assoc($realtor_query))
                                       {
                                          ?>
                                          <tr class="listPageTR">
                                            <td><?php echo @$realtor['first_name'];?></td>
                                                <td><?php echo @$realtor['last_name'];?></td>
						<td><?php echo @$realtor['organization_name'];?></td>
                                                    <td style="width:200px;"><?php echo @$realtor['address_line1'];?></td>
                                                        <td><?php echo @$realtor['city'];?></td>
                                                        <td><?php echo @$realtor['state'];?></td>
                                                       <td><?php echo @$realtor['country'];?></td>
                               <td><a href="client_detail.php?realtor_id=<?php echo $realtor['id'];?>" style="padding-left:10px;"><i class="fa fa-chevron-circle-right fa-lg" style="color:#000" title="View Client detail"></i></a></td>
                          <?php

                          $realtor_id=$realtor['id'];

                          $find_fav_realtor=mysqli_query($con,"SELECT count(*) as total FROM `company_favourite_realtor` where realtor_id='$realtor_id' and pc_admin_id='$loggedin_id'");

                          $find_fav_realtor1=mysqli_fetch_assoc($find_fav_realtor);

                          if($find_fav_realtor1['total']==0)
                          {
                          ?>

                           <td><a title="Add to favorites" onclick="favourite('<?php echo $realtor['id'];?>','<?php echo $loggedin_id;?>');"><i class="fa fa-heart-o" style="padding-left:30px"></i></a></td>
                           <?php

                       }

                       else{
                       	?>

                       	<td><a title="Already added to favourites"><i class="fa fa-heart" style="color:green;padding-left:30px"></i></a></td>

					<?php } ?>

                                          </tr>
                                          <tr><td class="listPageTRGap">&nbsp;</td></tr>

                                          <?php  } ?>

                                     </table></div>
                                  </div>
                                  <div class="panel" id="tab2" style="background-color: white;">
											<div class="col-md-12">
			<form name="realtorSearch" method="post" action="client.php?favourite=1">
	  <input type="text" class="form-control form-value" name="filter_realtor_favourite" placeholder="Search by Name,City,Organization and hit enter key" align="center" style="margin-left:25px;height:30px;width:96%" value="<?php echo @$_REQUEST['filter_realtor_favourite'];?>" onBlur="this.form.submit()"/>
			</form>
		</div>
		
                                    <hr class="space s">
									 <div style="width:100%;scrollbar-width: none;overflow-x: scroll;overflow-y:hidden">
                                    <table style="width:98%" align="center" class="table-striped" >
                                      <tr style="border:solid 2px #aad1d6;">
                                         <th><span adr_trans="label_first_name">Firstname</span></th>
                                         <th><span adr_trans="label_last_name">Lastname</span></th>
										<th><span adr_trans="label_organization">Organization</span></th>
                                         <th><span adr_trans="label_address" >Address</span></th>
                                            <th><span adr_trans="label_city">City</span></th>
                                               <th><span adr_trans="label_state">state</span></th>
                                               <th><span adr_trans="label_country">Country</span></th>
                                                  <th><span adr_trans="label_details">Details</span></th>
                                                  <th><span adr_trans="label_favourite">Favourite</span></td>
                                       </tr>
                                       <?php
																 $realtor_query1="";

			   if(@$_REQUEST['filter_realtor_favourite'])
				  {

				 $searchKey1=$_REQUEST['filter_realtor_favourite'];

			$conditions1="and (first_name like '%$searchKey1%' or last_name like '%$searchKey1%' or organization_name like '%$searchKey1%' or city like '%$searchKey1%')";

			$realtor_query1=mysqli_query($con,"select * from user_login where email_verified=1 and type_of_user='Realtor' $conditions1 and id in(select realtor_id from company_favourite_realtor where pc_admin_id='$loggedin_id')");

					}

				else
				{

		$realtor_query1=mysqli_query($con,"select * from user_login where email_verified=1 and type_of_user='Realtor' and id in(select realtor_id from company_favourite_realtor where pc_admin_id='$loggedin_id')");

				}
                                       // $realtor_query=mysqli_query($con,"select * from user_login where type_of_user='Realtor' and id in(select realtor_id from company_favourite_realtor where pc_admin_id='10')");
                                       while($realtor1=mysqli_fetch_assoc($realtor_query1))
                                       {
                                          ?>
                                          <tr class="listPageTR">
                                            <td><?php echo @$realtor1['first_name'];?></td>
                                                <td><?php echo @$realtor1['last_name'];?></td>
																									  <td><?php echo @$realtor1['organization_name'];?></td>
                                                    <td style="width:200px;"><?php echo @$realtor1['address_line1'];?></td>
                                                        <td><?php echo @$realtor1['city'];?></td>
                                                            <td><?php echo @$realtor1['state'];?></td>
                                                                <td><?php echo @$realtor1['country'];?></td>
                                                                    <td><a href="client_detail.php?realtor_id=<?php echo $realtor1['id'];?>" style="padding-left:10px"><i class="fa fa-chevron-circle-right fa-lg" style="color:#000" title="View Client detail"></i></a></td>
                                                                        <td><a title="Remove from favourites" onclick="unfavourite('<?php echo $realtor1['id'];?>','<?php echo $loggedin_id;?>');" style="text-align:center"><i class="fa fa-heart" style="color:green;padding-left:20px"></i></a></td>
                                          </tr>
                                           <tr><td class="listPageTRGap">&nbsp;</td></tr>
                                          <?php
                                      }
                                       ?>

                                     </table></div>

                                  </div>
																	<?php
                                    if(@$_REQUEST['favourite'])
																		{
																			?>
																			<script>
																			$("#click1").removeClass('active');
																			$("#click2").addClass('active');
																			$("#tab1").removeClass('active');
																			$("#tab2").addClass('active');

																			</script>
																			<?php
																		}
																	?>

                              </div>
                          </div>
          </div>
        </div>
</div>
</div>

<div id="tnc" class="box-lightbox white" style="padding:25px;border-radius:25px 25px 25px 25px;width:450px;height:230px;">
	 <div class="subtitle g" style="color:#333333">
	 	 <h5 style="color:#333333;font-style: italic;" align="center">“Fotopia is awesome! We recommend Realtors and Photo Company to join here”</h5>
    <br>
		 <h5 style="color:#333333" align="center" id="label_enter_the_email" adr_trans="label_enter_the_email">Enter the Email</h5>
			
				<center><span class="sub" id="error" style="color:green;"></span></center>
				<form   method="post" name="stdform" action="" onsubmit="">
				<input id="email1" name="email" placeholder="Email" type="email" autocomplete="off" onblur="this.value=this.value.trim()" class="form-control form-value" required>
				<input type="hidden" name="pc_admin_id" id="pc_admin_id" value="<?php echo $_SESSION['admin_loggedin_id']; ?>"/><br>
				<center><button class="btn adr-save" name="link" id="send" ><span adr_trans="label_send">Send</span></button></center>
				</form>
				<hr class="space l">




				</div>
							 </div>



<?php if(@$_REQUEST['f']==1)
{ ?>
<script>

$("#click2").addClass("active");
$("#click1").removeClass("active");



$("#tab2").addClass("active");
$("#tab1").removeClass("active");


</script>
<?php } ?>



		<?php include "footer.php";  ?>
