<?php
ob_start();

include "connection1.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function email($order_id,$con)
{
	/* Exception class. */
	require 'C:\PHPMailer\src\Exception.php';

	/* The main PHPMailer class. */
	require 'C:\PHPMailer\src\PHPMailer.php';

	/* SMTP class, needed if you want to use SMTP. */
	require 'C:\PHPMailer\src\SMTP.php';


	$mail = new PHPMailer(true);
	$mail->isSMTP();
	$mail->Host = $_SESSION['emailHost'];
	$mail->SMTPAuth = true;
	// //paste one generated by Mailtrap
	// //paste one generated by Mailtrap
	$mail->Username =$_SESSION['emailUserID'];
	$mail->Password =$_SESSION['emailPassword'];
	$mail->SMTPSecure = 'tls';
	$mail->Port = $_SESSION['emailPort'];

	//From email address and name
	$mail->From = $_SESSION['emailUserID'];
	$mail->FromName = "Fotopia";

  $get_orderdetail_query=mysqli_query($con,"SELECT * from orders WHERE id='$order_id'");
  $get_detail=mysqli_fetch_array($get_orderdetail_query);
  $home_seller_id=$get_detail['home_seller_id'];
  $pc_admin_id=$get_detail['pc_admin_id'];
  $get_lead_from_column_query=mysqli_query($con,"select * from home_seller_info where id=$home_seller_id");
  $get_lead_detail=mysqli_fetch_array($get_lead_from_column_query);
  $get_pcadmin_profile_query=mysqli_query($con,"SELECT * FROM `photo_company_profile` WHERE pc_admin_id=$pc_admin_id");
  $get_profile=mysqli_fetch_assoc($get_pcadmin_profile_query);
  $pcadmin_email=$_SESSION['admin_loggedin_email'];
  $pcadmin_name=$_get_profile['first_name'];
  $pcadmin_contact=$get_profile['contact_number'];
	$photographer_id=@$get_detail['photographer_id'];
	$realtor_id=@$get_detail['realtor_id'];
	$get_realtor_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$realtor_id'");
	$get_name_realtor=mysqli_fetch_assoc($get_realtor_name_query);
	$realtor_email=@$get_name_realtor["email"];
	$realtor_name=$get_name_realtor['first_name'];
	$get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
	$get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
	$photographer_Name=@$get_name["first_name"]." ".@$get_name["last_name"];
	$photographer_email=@$get_name["email"];
	$photographer_name=$get_name['first_name'];
	$csr_id=@$get_name['csr_id'];
	$csr_email="";
	$pc_admin_user_id=@$get_name['pc_admin_user_id'];
	$get_hs_detail_query=mysqli_query($con,"select * from home_seller_info where id=$home_seller_id");
	 $get_hs_detail=mysqli_fetch_array($get_hs_detail_query);
	if($csr_id==0 && $pc_admin_user_id!=0)
	{
	$pc_admin_user1=mysqli_query($con,"select * from photo_company_admin where id='$pc_admin_user_id'");
	$pc_admin_user=mysqli_fetch_array($pc_admin_user1);
	$csr_email=$pc_admin_user['email'];
	$csr_name=$pc_admin_user['first_name'];
	}
	if($csr_id!=0)
	{
	$get_csrdetail_query=mysqli_query($con,"SELECT * FROM admin_users where id='$csr_id'");
	$get_csrdetail=mysqli_fetch_assoc($get_csrdetail_query);
	$csr_email=$get_csrdetail['email'];
	$csr_name=$get_csrdetail['first_name'];
	}
	 $from_date1=$get_detail['session_from_datetime'];
    $to_date1=$get_detail['session_to_datetime'];

  if($get_lead_detail['lead_from']=="homeseller")
  {
    $from_date=date_create($get_detail['session_from_datetime']);
    $to_date=date_create($get_detail['session_to_datetime']);
    $mail->addAddress($get_lead_detail['email']);
		if(!empty($csr_email)){$mail->AddCC($csr_email);}if(!empty($photographer_email)){$mail->AddCC($photographer_email);}if(!empty($pcadmin_email)){$mail->AddCC($pcadmin_email);}
		$mail->addReplyTo($_SESSION['emailUserID'], "Reply");
		$mail->isHTML(true);
    $mail->Subject = "Order Placed";
    $mail->Body = "<html><head><style>.titleCss {font-family: \"Roboto\",Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;color:#0275D8 }.emailCss { width:100%;border:solid 1px #DDD;font-family: \"Roboto\",Helvetica,Arial,sans-serif; } </style></head><table cellpadding=\"5\" class=\"emailCss\"><tr><td align=\"left\"><img src=\"".$_SESSION['project_url']."logo.png\" /></td><td align=\"center\" class=\"titleCss\">ORDER PLACED SUCCESSFULLY</td>
    <td align=\"right\"><img src=\"".$_SESSION['project_url'].$get_profile['logo_image_url']."\" width=\"110\" height=\"80\"/></td>  </tr><tr><td align=\"left\">".$_SESSION['support_team_email']."<br>".$_SESSION['support_team_phone']."</td><td colspan=\"2\" align=\"right\">".strtoupper($get_profile['organization_name'])."<br>".$pcadmin_email."<br>".$pcadmin_contact."</td></tr><tr><td colspan=\"2\"><br><br>";
    //$mail->AltBody = "This is the plain text version of the email content";

    $mail->Body.="Dear {{Home seller name}},<br><br>
  New Order has been placed successfully,<br>
 Your Order #{{Order_ID}}, Order appointment Session Date & time {{From time hh:mm:ss}} to {{To time hh:mm:ss}}<br>
 Thanks for choosing us, have a good day.<br><br>
 Thanks,<br>
 Fotopia Team";

    $mail->Body=str_replace('{{Order_ID}}', $order_id , $mail->Body);
    $mail->Body=str_replace('{{Home seller name}}', $get_lead_detail['name'] , $mail->Body);
    $mail->Body=str_replace('{{From time hh:mm:ss}}',date_format($from_date,"d F Y g:ia") , $mail->Body);
    $mail->Body=str_replace('{{To time hh:mm:ss}}', date_format($to_date,"d F Y g:ia")  , $mail->Body);

    $mail->Body.="<br><br></td></tr></table></html>";
  }
  else{
  //this is for realtor scenario
    $from_date=date_create($get_detail['session_from_datetime']);
    $to_date=date_create($get_detail['session_to_datetime']);
    $mail->addAddress($get_lead_detail['email']);
		if(!empty($csr_email)){$mail->AddCC($csr_email);}if(!empty($pcadmin_email)){$mail->AddCC($pcadmin_email);}if(!empty($realtor_email)){$mail->AddCC($realtor_email);}if(!empty($photographer_email)){$mail->AddCC($photographer_email);}
    $mail->addAddress($get_lead_detail['request_email']);
		$mail->addReplyTo($_SESSION['emailUserID'], "Reply");
		$mail->isHTML(true);
    $mail->Subject = "Order Placed";
    $mail->Body = "<html><head><style>.titleCss {font-family: \"Roboto\",Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;color:#0275D8 }.emailCss { width:100%;border:solid 1px #DDD;font-family: \"Roboto\",Helvetica,Arial,sans-serif; } </style></head><table cellpadding=\"5\" class=\"emailCss\"><tr><td align=\"left\"><img src=\"".$_SESSION['project_url']."logo.png\" /></td><td align=\"center\" class=\"titleCss\">ORDER PLACED SUCCESSFULLY</td>
    <td align=\"right\"><img src=\"".$_SESSION['project_url'].$get_profile['logo_image_url']."\" width=\"110\" height=\"80\"/></td>  </tr><tr><td align=\"left\">".$_SESSION['support_team_email']."<br>".$_SESSION['support_team_phone']."</td><td colspan=\"2\" align=\"right\">".strtoupper($get_profile['organization_name'])."<br>".$pcadmin_email."<br>".$pcadmin_contact."</td></tr><tr><td colspan=\"2\"><br><br>";
    //$mail->AltBody = "This is the plain text version of the email content";

    $mail->Body.="Hi,<br><br>
   New Order has been placed successfully,<br>
   Your Order #{{Order_ID}}, Order appointment Session Date & time {{From time hh:mm:ss}} to {{To time hh:mm:ss}}<br>
   Thanks for choosing us, have a good day.<br><br>
   Thanks,<br>
   Fotopia Team";

  $mail->Body=str_replace('{{Order_ID}}', $order_id , $mail->Body);
  $mail->Body=str_replace('{{From time hh:mm:ss}}',date_format($from_date,"d F Y g:ia") , $mail->Body);
  $mail->Body=str_replace('{{To time hh:mm:ss}}', date_format($to_date,"d F Y g:ia")  , $mail->Body);

    $mail->Body.="<br><br></td></tr></table></html>";
  }
   
  
  $to_emails=$realtor_name."--".$realtor_email.",".$pcadmin_name."--".$pcadmin_email;
	if(!empty($csr_email))
	{
    // addcc change to addaddress for calender invite purpose.
	$mail->addAddress($csr_email);
 
  $to_emails=$to_emails.",".$csr_name."--".$csr_email;
	}
	$mail->addAddress($pcadmin_email);
	if(!empty($photographer_email))
	{
	$mail->addAddress($photographer_email);
  $photographer_name=$get_name['first_name'];
  $to_emails=$to_emails.",".$photographer_name."--".$photographer_email;
	}
  $to_emails=$to_emails.",".$get_hs_detail['name']."--".$get_hs_detail['email'];
	$mail->addAddress($get_hs_detail['email']);

if(!empty($from_date1) && !empty($from_date1))
{
	 // echo $mail->Body;
	 // exit;
include "CalendarEvent.php";

$from_name = "Fotopia";        
$from_address = "alerts@fotopia.no";        
$to_name = "Photographer / PCAdmin";        
$to_address = $to_emails;        
$startTime = $from_date1;        
$endTime = $to_date1;       
$subject = $mail->Subject;        
$description = "ADR USA discussion";        
$location = $get_detail['property_address'];
$domain="fotopia.no";
$UID=date("Ymd\TGis", strtotime($startTime)).rand()."@".$domain;
mysqli_query($con,"update orders set Invite_UID='$UID' where id='$order_id'");
$icalIs=sendIcalEvent($from_name, $from_address, $to_name, $to_address, $startTime, $endTime, $subject,     
$description, $location,"REQUEST",$UID);
$mail->AltBody = $icalIs;
$mail->Ical = $icalIs;
}

	try {
	    $mail->send();
	    echo "Message has been sent successfully";
	} catch (Exception $e) {
		// echo $e->getMessage();
	  //   echo "Mailer Error: " . $mail->ErrorInfo;
	}
}

   if(isset($_REQUEST['save_appointment']))
   {

     $property =$_REQUEST["property"];
     $plan=$_REQUEST["plan"];

     $area=$_REQUEST["area"];
     $address_same=@$_REQUEST["address_same"];
     $property_address=$_REQUEST["property_address"];
     $property_city=$_REQUEST["property_city"];
     $property_state=$_REQUEST["property_state"];
     $property_country=$_REQUEST["property_country"];
     $property_zip=$_REQUEST["property_zip"];
$pht_id="";
if(empty($_REQUEST["property_contact_mobile"]))
{
  $property_contact_mobile="";
}
else
{
  $property_contact_mobile = $_REQUEST["property_contact_mobile"];
}

if(empty($_REQUEST["property_contact_email"]))
{
  $property_contact_email="";
}
else
{
  $property_contact_email = $_REQUEST["property_contact_email"];
}


	   $rental_dormitory=@$_REQUEST["rental_dormitory"];
	   if(@$_REQUEST['pht_name']!="")
	   {
	   $pht_id=$_REQUEST["pht_name"];
	   }
	   else
	   {
	   $pht_id=$_REQUEST["Photographer_id"];
	   }
     //--------------the line get from photographer_id value-------------------------------------------//
     //$product=implode(",",$_REQUEST["product"]);
     $notes=$_REQUEST["notes"];
     $status=1;
     $home_seller_id=$_REQUEST["hs_id"];

     $created_id=$_SESSION["admin_loggedin_id"];
     //-------------------------------------------------get value request method------------------------------------------//
     $from_date=$_REQUEST["from"];
     $to_date=$_REQUEST["to"];
$chk_from="";
$chk_to="";

     //-------------------------------------------------timestam format change---------------------------------------------//
     if(@$_REQUEST['from'])
	 {
	 $from_exp=explode("T",$from_date);
      $chk_from=$from_exp[0]." ".$from_exp[1];
	  }
	 if(@$_REQUEST['to'])
	 {
	 $to_exp=explode("T",$to_date);
$chk_to=$to_exp[0]." ".$to_exp[1];
}
     //
     //-------------------------------------------------t replace to space -----------------------------------------------//


    //
		if(empty($_REQUEST["due"]))
		{
			$added_date=date("Y-m-d H:i:s",strtotime('+24 hours', strtotime($chk_to)));
			$added_exp=explode(" ",$added_date);
			$due_date=$added_exp[0]."T".$added_exp[1];
		//	echo $due_date;
		}
		else
		{
			$due_date=$_REQUEST["due"];
		}
    //
		 $chk_due=$_REQUEST["due"];

$pc_admin_id1=$_REQUEST['pc_admin_id'];
//$Photographer_id1=$_REQUEST['Photographer_id'];
$Photographer_id1=$pht_id;

						 $loggedin_name=$_SESSION['admin_loggedin_name'];
						 $loggedin_id=$_SESSION['admin_loggedin_id'];
             $loggedin_type=$_SESSION['admin_loggedin_type'];
             // echo "select * from user_login WHERE id=$pht_id";
							$user_details_query=mysqli_query($con,"select * from user_login WHERE id='$Photographer_id1'");
							$user_details_query1=mysqli_fetch_assoc($user_details_query);
							$superCSR_ID=$user_details_query1['pc_admin_id'];
							$subCSR_ID=$user_details_query1['csr_id'];
							$photographer_Name=$user_details_query1['first_name']." ".$user_details_query1["last_name"];
							$email_id=$user_details_query1["email"];
	$editProduct=0;
if(@$_REQUEST['od']!="")
{
$editProduct=1;

$order_id=$_REQUEST['od'];

$get_realtor_details=mysqli_query($con,"select * from orders WHERE id='$order_id'");
$get_realtor_id=mysqli_fetch_assoc($get_realtor_details);

$realtor_id = $get_realtor_id['created_by_id'];
$_SESSION['old_from_time']= $get_realtor_id['session_from_datetime'];
$_SESSION['old_to_time']= $get_realtor_id['session_to_datetime'];

 mysqli_query($con,"update orders set `home_seller_id`='$home_seller_id', `property_type`='$property', `number_of_floor_plans`='$plan', `area`='$area',`property_address`='$property_address',`property_city`='$property_city',`property_state`='$property_state',`property_country`='$property_country',`property_zip`='$property_zip',`property_contact_mobile`='$property_contact_mobile',`property_contact_email`='$property_contact_email',`address_same`='$address_same',`rental_dormitory`='$rental_dormitory',  `photographer_id`='$Photographer_id1', `session_from_datetime`='$chk_from', `session_to_datetime`='$chk_to', `order_due_date`='$chk_due', `booking_notes`='$notes',`pc_admin_id`='$pc_admin_id1',`csr_id`='$subCSR_ID',`created_datetime`=now() where id='$_REQUEST[od]'");

mysqli_query($con,"delete from `appointments` where order_id='$_REQUEST[od]'");

$get_appointment=mysqli_query($con,"SELECT * FROM appointments WHERE photographer_id=$Photographer_id1 and ((from_datetime <= '$chk_from' AND to_datetime > '$chk_from') OR (from_datetime < '$chk_to' AND to_datetime >= '$chk_to'))");

 $number=mysqli_num_rows($get_appointment);
if($number>0)
{
header("location:create_appointment.php?hs_id=$home_seller_id&&pc_admin_id=$pc_admin_id1&&Photographer_id=$Photographer_id1&&od=$order_id&appdup=1");exit;

}

 mysqli_query($con,"INSERT INTO `appointments` (`order_id`,`created_by_id`, `photographer_id`, `home_seller_id`, `from_datetime`, `to_datetime`, `status`, `active`) VALUES ('$order_id','$realtor_id', '$Photographer_id1', '$home_seller_id', '$chk_from', '$chk_to', '1', '1')");




 $insert_action=mysqli_query($con,"INSERT INTO `user_actions`( `module`, `action`, `action_done_by_name`, `action_done_by_id`,`action_done_by_type`,`photographer_id`, `Realtor_id`,`pc_admin_id`,`csr_id`,`action_date`) VALUES ('Appointment','Updated','$loggedin_name',$loggedin_id,'$loggedin_type',$pht_id,$realtor_id,$pc_admin_id1,$subCSR_ID,now())");
}
else
{
$realtor_idIS=0;
$realtorID1=mysqli_query($con,"select id from user_login where type_of_user='Realtor' and  email=(select request_email from home_seller_info where lead_from='realtor' and id='$home_seller_id')");
$realtorID1EX=mysqli_num_rows($realtorID1);
if($realtorID1EX>0)
{
$realtorID=mysqli_fetch_array($realtorID1);
$realtor_idIS=$realtorID['id'];
}
    mysqli_query($con,"INSERT INTO `orders` (`home_seller_id`,`realtor_id`, `property_type`, `number_of_floor_plans`, `area`,`property_address`,`property_city`,`property_state`,`property_country`,`property_zip`,`property_contact_mobile`,`property_contact_email`,`address_same`,`rental_dormitory`,  `photographer_id`, `session_from_datetime`, `session_to_datetime`, `order_due_date`, `booking_notes`, `created_by_id`,`created_by_type`,`pc_admin_id`,`csr_id`,`created_datetime`, `status_id`) VALUES ($home_seller_id,'$realtor_idIS','$property', '$plan', '$area','$property_address','$property_city','$property_state','$property_country','$property_zip','$property_contact_mobile','$property_contact_email','$address_same','$rental_dormitory', '$Photographer_id1', '$chk_from', '$chk_to', '$chk_due', '$notes', '$created_id','$_SESSION[admin_loggedin_type]','$pc_admin_id1','$subCSR_ID',now(), '$status')");
$order_id=mysqli_insert_id($con);

$get_appointment=mysqli_query($con,"SELECT * FROM appointments WHERE photographer_id=$Photographer_id1 and ((from_datetime <= '$chk_from' AND to_datetime > '$chk_from') OR (from_datetime < '$chk_to' AND to_datetime >= '$chk_to'))");

 $number=mysqli_num_rows($get_appointment);
if($number>0)
{
header("location:create_appointment.php?hs_id=$home_seller_id&&pc_admin_id=$pc_admin_id1&&Photographer_id=$Photographer_id1&&od=$order_id&appdup=1");exit;

}
 mysqli_query($con,"INSERT INTO `appointments` (`order_id`, `created_by_id`, `photographer_id`, `home_seller_id`, `from_datetime`, `to_datetime`, `status`, `active`) VALUES ('$order_id', '$created_id', '$Photographer_id1', '$home_seller_id', '$chk_from', '$chk_to', '1', '1')");

  email($order_id,$con);


 $insert_action=mysqli_query($con,"INSERT INTO `user_actions`( `module`, `action`, `action_done_by_name`, `action_done_by_id`,`action_done_by_type`,`photographer_id`,`pc_admin_id`,`csr_id`,`action_date`) VALUES ('Appointment','Created','$loggedin_name',$loggedin_id,$loggedin_type,$pht_id,$pc_admin_id1,$subCSR_ID,now())");
}
//Sending email
//email($photographer_Name,$order_id,$chk_from,$email_id);


if($_REQUEST['edit']==1){

	header("location:select_products.php?od=$order_id&pc_admin_id=$pc_admin_id1&Photographer_id=$Photographer_id1&hs_id=$home_seller_id&u=$editProduct&edit=1");

}

else{

header("location:select_products.php?od=$order_id&pc_admin_id=$pc_admin_id1&Photographer_id=$Photographer_id1&hs_id=$home_seller_id&u=$editProduct");

}
	   



}
?>


<?php include "header.php";  ?>
 <div class="section-empty bgimage7">
        <div class="container" style="margin-left:0px;height:inherit;width:100%">
            <div class="row">
			<hr class="space s">
                <div class="col-md-2" >
				<?php
				$calDate="";
				if(isset($_SESSION['date'])!="")
				{
				$calDate=$_SESSION['date'];
				}
				if(isset($_SESSION['fromDatetime'])!="")
				{
				$calDate=$_SESSION['fromDatetime'];
				}
				?>
				<input type="hidden" name="calDate" id="calDate" value="<?php echo $calDate; ?>" />
	<?php include "sidebar.php"; ?>
  <style>

  	#calendar{

  background: #FFF!important;
}

.breadcrumb1 {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  border-radius: 6px;
  overflow: hidden;
  margin-top: 43px!important;
  text-align: center;
  top: 50%;
  width: 100%;
  height: 57px;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  z-index: 1;
  background-color: #ddd;
  font-size: 14px;

}

.breadcrumb1 a {
  position: relative;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-flex: 1;
      -ms-flex-positive: 1;
          flex-grow: 1;
  text-decoration: none;
  margin: auto;
  height: 100%;
  padding-left: 38px;
  padding-right: 0;
  color: #666;
}

.breadcrumb1 a:first-child {
  padding-left: 10px;

}

.breadcrumb1 a:last-child {
  padding-right: 15.2px;
}

#firstStep:after {
  content: "";
  position: absolute;
  display: inline-block;
  width: 57px;
  height: 57px;
  top: 0;
  right: -28.14815px;
  background-color: #DDD;
  border-top-right-radius: 5px;
  -webkit-transform: scale(0.707) rotate(45deg);
          transform: scale(0.707) rotate(45deg);
  z-index: 1;

}
#secondStep:after {
  content: "";
  position: absolute;
  display: inline-block;
  width: 57px;
  height: 57px;
  top: 0;
  right: -28.14815px;
  background-color: #000;
  border-top-right-radius: 5px;
  -webkit-transform: scale(0.707) rotate(45deg);
          transform: scale(0.707) rotate(45deg);
  z-index: 1;
}
.breadcrumb1 a:last-child:after {
  content: none;
}

.breadcrumb__inner {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
  margin: auto;
  z-index: 2;
}

.breadcrumb__title {
  font-weight: bold;
}

#secondStep:hover {
background-color:#aad1d6;
}

#secondStep:after {
background-color:#aad1d6;
}

@media all and (max-width: 1000px) {
  .breadcrumb1 {
    font-size: 12px;
  }
}
@media all and (max-width: 710px) {
  .breadcrumb__desc {
    display: none;
  }

  .breadcrumb1 {
    height: 38px;
  }

  .breadcrumb1 a {
    padding-left: 25.33333px;
  }

  .breadcrumb a:after {
    content: "";
    width: 38px;
    height: 38px;
    right: -19px;
    -webkit-transform: scale(0.707) rotate(45deg);
            transform: scale(0.707) rotate(45deg);
  }
}

.fc .fc-button .fc-icon
{
font-size:0.8em!important;
}
.fc-day-mon,.fc-day-tue,.fc-day-wed,.fc-day-thu,.fc-day-fri
{
background:#CCEDFC!important;
border:solid 1px #01A8F2!important;
}
.fc-day-sat,.fc-day-sun
{
background:#EEEEEE!important;
border:solid 1px #01A8F2!important;
}
.fc-day-today
{
background:#8ed0ed!important;
border:solid 1px #01A8F2!important;
}
.btn-default
{
border-radius:0px;
color:#000!important;
background:#aad1d6!important;
border:none;
}
.status1{



		background-color:#86C4F0!important;



        color:#000!important;



        }
.status4,.status5,.status6{
		background-color:#F58883!important;
		color:#000!important;
		 }


        .status3
 {

        color:#000!important;

		background-color:#76EA97!important;

        }
        .status2,.status7 {

		background-color:#FF8400!important;

        color:#000!important;

        }
	.fc .fc-toolbar.fc-header-toolbar
			{
			padding:3px!important;
			font-size:10px!important;
		}
		.fc-toolbar-title
		{
		font-size:10px!important;
		}
		.statusBUSY
{
 pointer-events: none;
	color:#000;
	padding-left:5px;
background: repeating-linear-gradient(
    45deg,
    transparent,
    transparent 10px,
    #ccc 2px,
    #DDD 12px
  ),
  /* on "bottom" */
  linear-gradient(
    to bottom,
    #eee,
    #999
  )!important;

}

.breadcrumb__title
{
font-size:12px!important;
}
.breadcrumb__desc
{
font-size:11px!important;
}
  </style>
  				<link href='../lib/main.css' rel='stylesheet' />

  <script src='../lib/main.js'></script>

 <?php
 $todayIs="";
 if(isset($_SESSION['date']))
 {
 $todayIs=$_SESSION['date'];
 }
 if(isset($_SESSION['fromDatetime']))
 {
 $todayIs=$_SESSION['fromDatetime'];
 $todayIs1=explode("T",$todayIs);
 $todayIs=$todayIs1[0];
 }
 ?>

  <script>

  	  function get_states(cityIs)
 {
  
if(cityIs!="")
  {
  $("#validation_message").css("display","none");
  $("#validation_message").html("");
  const xhttp = new XMLHttpRequest();
  xhttp.onload = function() {
  var split=this.responseText.split("zipcode");
    document.getElementById("property_state").innerHTML = split[0];
    // document.getElementById("property_zip").value= split[1];
  
    }
  xhttp.open("GET", "../getState.php?city="+cityIs, true);
  xhttp.send();
 }
  else
  {
    $("#validation_message").css("display","block");
    $("#validation_message").html("(Please select your city!.)");
  }
}  

 document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
	var today123='<?php echo $todayIs; ?>';
	var today ="";
	if(today123=='')
	{
today = new Date().toISOString().slice(0, 10)
}
else
{
today=today123;
}
	//alert(today123);

$.ajax({
      url: "photographer_events.php?photographer_id=<?php echo $_REQUEST["Photographer_id"]; ?>",
      modal: true,
	   dataType: 'JSON',
	  success: function(response){
	 // eventData=JSON.stringify(response);
	//alert(eventData);

    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialDate: today,
      initialView: 'timeGridDay',
	  contentHeight: 600,
	   fixedWeekCount: false,
      nowIndicator: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridDay'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      selectable: true,
      selectMirror: true,
      dayMaxEvents: true,
	  displayEventTime:true,// allow "more" link when too many events
      eventSources: [
    'photographer_events.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>',
   'photographer_busy.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&csr_id=<?php echo @$_REQUEST['csr_id']; ?>'
  ],

    });

    calendar.render();



	}
	});


  });

  function setSecondDate1()
  {
var days = 1;
  var d = new Date(document.getElementById("from").value);
//alert(d);
var year = d.getFullYear();
var month = d.getMonth()+1;
var day = d.getDate();

if (day < 10) {
  day = '0' + day;
}
if (month < 10) {
  month = '0' + month;
}


var dateIs=year+"-"+month+"-"+day;


    var calendarEl = document.getElementById('calendar');
var today = new Date().toISOString().slice(0, 10)
//var today =d;

$.ajax({
      url: "photographer_events.php?photographer_id=<?php echo $_REQUEST["Photographer_id"]; ?>",
      modal: true,
	   dataType: 'JSON',
	  success: function(response){
	 // eventData=JSON.stringify(response);
	//alert(eventData);

    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialDate: today,
      initialView: 'timeGridDay',
	  contentHeight: 480,
	   fixedWeekCount: false,
      nowIndicator: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridDay,listWeek'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      selectable: true,
      selectMirror: true,
      dayMaxEvents: true,
	  displayEventTime:true,// allow "more" link when too many events
      eventSources: [
    'photographer_events.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>',
    'photographer_busy.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&csr_id=<?php echo @$_REQUEST['csr_id']; ?>'
  ],
    });

    calendar.render();
calendar.gotoDate(dateIs);

	}
	});


	if(d!='Invalid Date')
	{
 $("#to").attr("min",d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours())+":"+zeroPadded(d.getMinutes()));


   $("#due").attr("min",d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate()));
 //document.getElementById("due").value = d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate());
  }
 // alert(booking_chk1());
booking_chk1();



  var from=document.getElementById('from').value;

    var to=document.getElementById('to').value;
  //	alert("to"+to);

    var fromNew = new Date(document.getElementById("from").value);
//		alert("fromNew"+fromNew);
  var fromNew1=fromNew.getFullYear()+"-"+zeroPadded(fromNew.getMonth()+1)+"-"+zeroPadded(fromNew.getDate())+" "+zeroPadded(fromNew.getHours())+":"+zeroPadded(fromNew.getMinutes())+":00";
  //  alert("fromNew1"+fromNew1);
  var toNew = new Date(document.getElementById("to").value);
//	alert("toNew"+toNew);
  var toNew1=toNew.getFullYear()+"-"+zeroPadded(toNew.getMonth()+1)+"-"+zeroPadded(toNew.getDate())+" "+zeroPadded(toNew.getHours())+":"+zeroPadded(toNew.getMinutes())+":00";


var bFound=parseInt($("#BookingFound").val());
//alert(bFound);
    if(bFound>0)
    {
	//alert("coming123");

     var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		$("#appointments_exist_error").html("Det er en annen avtale planlagt for den valgte fotografen mellom <br>"+fromNew1+" og "+toNew1+", Velg en annen dato og tid.");
		}
		else
		{
		$("#appointments_exist_error").html("There is another appoinment scheduled for the selected photographer <br> in between "+fromNew1+" and "+toNew1+", Kindly choose different Date & Time.");
		}

   //  $("#appointments_exist_error").show();
	// return false;
    }
    if(bFound==0)
    {
//	alert("coming 0");
    //  alert("no appointment");
	$("#appointments_exist_error").hide();
	//$("#appointmentForm").submit();
	return true;
    }


  }


  function setSecondDate()
  {
var days = 1;
  var d = new Date(document.getElementById("from").value);

var year = d.getFullYear();
var month = d.getMonth()+1;
var day = d.getDate();

if (day < 10) {
  day = '0' + day;
}
if (month < 10) {
  month = '0' + month;
}


var dateIs=year+"-"+month+"-"+day;






    var calendarEl = document.getElementById('calendar');
var today = new Date().toISOString().slice(0, 10)
//var today =d;

$.ajax({
      url: "photographer_events.php?photographer_id=<?php echo $_REQUEST["Photographer_id"]; ?>",
      modal: true,
	   dataType: 'JSON',
	  success: function(response){
	 // eventData=JSON.stringify(response);
	//alert(eventData);

    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialDate: today,
      initialView: 'timeGridDay',
	  contentHeight: 480,
	   fixedWeekCount: false,
      nowIndicator: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridDay,listWeek'
      },
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      selectable: true,
      selectMirror: true,
      dayMaxEvents: true,
	  displayEventTime:true,// allow "more" link when too many events
      eventSources: [
    'photographer_events.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>',
   'photographer_busy.php?photographer_id=<?php echo $_REQUEST['Photographer_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&csr_id=<?php echo @$_REQUEST['csr_id']; ?>'
  ],
    });

    calendar.render();
calendar.gotoDate(dateIs);

	}
	});

 $("#to").attr("min",d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours())+":"+zeroPadded(d.getMinutes()));
  document.getElementById("to").value = d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours()+1)+":"+zeroPadded(d.getMinutes());

 $("#to").attr("value",d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours()+1)+":"+zeroPadded(d.getMinutes()));
  document.getElementById("to").value = d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours()+1)+":"+zeroPadded(d.getMinutes());

   $("#due").attr("min",d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate()));
 // document.getElementById("due").value = d.getFullYear()+"-"+zeroPadded(d.getMonth()+1)+"-"+zeroPadded(d.getDate())+"T"+zeroPadded(d.getHours()+1)+":"+zeroPadded(d.getMinutes());
booking_chk();


 // d.setDate(d.getDate() + 1);

  // d.setTime(d.getTime()+ 1);


  }



  function zeroPadded(val) {
  if (val >= 10)
    return val;
  else
    return '0' + val;
}

  //---------------------------------------- validate greater than or not-----------------------------//


var photographer_id;
  function Get_Products()
{
  var value= $('#pht').val();

  var photographer_id=$('#options [value="' + value + '"]').data('value');

 $('#photo_id').val(photographer_id);

}
var valIs="";
function showHideFloors(valIs)
{
if(valIs=="EmptyLand")
{
$("#plan").attr("readonly","readonly");
$("#plan").attr("style","background:#CCC");
$("#plan").removeAttr("placeholder");
$("#plan").val("");
}
else
{
$("#plan").removeAttr("readonly");

$("#plan").attr("style","background:#E8EFFC");
$("#plan").attr("placeholder","Enter the floor number");
}
}

             function setpropertyAddress(){

var property_address="<?php if(isset($_SESSION['property_address'])) { echo $_SESSION['property_address']; } else { echo ""; } ?>";
var property_city="<?php if(isset($_SESSION['property_city'])) { echo $_SESSION['property_city']; } else { echo ""; } ?>";
var property_state="<?php if(isset($_SESSION['property_state'])) { echo $_SESSION['property_state']; } else { echo ""; } ?>";
var property_country="<?php if(isset($_SESSION['property_country'])) { echo $_SESSION['property_country']; } else { echo ""; } ?>";
var property_zip="<?php if(isset($_SESSION['property_zip'])) { echo $_SESSION['property_zip']; } else { echo ""; } ?>";
var property_contact_mobile="<?php if(isset($_SESSION['property_contact_mobile'])) { echo $_SESSION['property_contact_mobile']; } else { echo ""; } ?>";
var property_contact_email="<?php if(isset($_SESSION['property_contact_email'])) { echo $_SESSION['property_contact_email']; } else { echo ""; } ?>";


              if($("#address_same").prop('checked') == true)
                {
                $("#property_address").val("");
                $("#property_city").val("");
                $("#property_state").val("");
                $("#property_country").val("");
                $("#property_zip").val("");
                $("#property_contact_mobile").val("");
                $("#property_contact_email").val("");

                $("#property_address").removeAttr("readonly");
                $("#property_city").removeAttr("readonly");
                $("#property_state").removeAttr("readonly");
                $("#property_country").removeAttr("readonly");
                $("#property_zip").removeAttr("readonly");
                $("#property_contact_mobile").removeAttr("readonly");
                $("#property_contact_email").removeAttr("readonly");
                }
                else
                {
                $("#property_address").val(property_address);
                $("#property_city").val(property_city);
                $("#property_state").val(property_state);
                $("#property_country").val(property_country);
                $("#property_zip").val(property_zip);
                $("#property_contact_mobile").val(property_contact_mobile);
                $("#property_contact_email").val(property_contact_email);

                $("#property_address").attr("readonly","readonly");
                $("#property_city").attr("readonly","readonly");
                $("#property_state").attr("readonly","readonly");
                $("#property_country").attr("readonly","readonly");
                $("#property_zip").attr("readonly","readonly");
                $("#property_contact_mobile").attr("readonly","readonly");
                $("#property_contact_email").attr("readonly","readonly");
                }
             }




function booking_chk()
  {

    var from=document.getElementById('from').value;

    var to=document.getElementById('to').value;
  //	alert("to"+to);
   var photo_id='<?php echo @$_REQUEST['Photographer_id']; ?>';
  //  alert("photo_id"+photo_id);

    var fromNew = new Date(document.getElementById("from").value);
//		alert("fromNew"+fromNew);
  var fromNew1=fromNew.getFullYear()+"-"+zeroPadded(fromNew.getMonth()+1)+"-"+zeroPadded(fromNew.getDate())+" "+zeroPadded(fromNew.getHours())+":"+zeroPadded(fromNew.getMinutes())+":00";
  //  alert("fromNew1"+fromNew1);
  var toNew = new Date(document.getElementById("to").value);
//	alert("toNew"+toNew);
  var toNew1=toNew.getFullYear()+"-"+zeroPadded(toNew.getMonth()+1)+"-"+zeroPadded(toNew.getDate())+" "+zeroPadded(toNew.getHours())+":"+zeroPadded(toNew.getMinutes())+":00";
   //alert("toNew1"+toNew1);
 // d.setDate(d.getDate() + 1);

  // d.setTime(d.getTime()+ 1);


var od='<?php echo @$_REQUEST["od"]; ?>';
   var value= $('#pht').val();
   var a=0;
   var xhttp= new XMLHttpRequest();
   console.log(photo_id);
   console.log(fromNew);
    console.log(toNew);
  xhttp.onreadystatechange = function()
  {
    if(this.readyState == 4 && this.status == 200){

      a=parseInt(this.responseText);
       $("#BookingFound").val(a);

      if(a>0)
    {
     var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		$("#appointments_exist_error").html("Det er en annen avtale planlagt for den valgte fotografen mellom <br>"+fromNew1+" og "+toNew1+", Velg en annen dato og tid.");
		}
		else
		{
		$("#appointments_exist_error").html("There is another appoinment scheduled for the selected photographer <br> in between "+fromNew1+" and "+toNew1+", Kindly choose different Date & Time.");
		}
     $("#appointments_exist_error").show();
	 $("#BookingFound").val(a);
    return false;
    }
    else
    {
    //  alert("no appointment");
	$("#appointments_exist_error").hide();

    return true;
    }

    }
  };
  xhttp.open("GET","check_appointment.php?photographer_id="+photo_id+"&fromDate="+fromNew1+"&toDate="+toNew1+"&od="+od,true);
  xhttp.send();
  }
function booking_chk1()
  {

    var from=document.getElementById('from').value;

    var to=document.getElementById('to').value;
  //	alert("to"+to);
   var photo_id='<?php echo @$_REQUEST['Photographer_id']; ?>';
  //  alert("photo_id"+photo_id);

    var fromNew = new Date(document.getElementById("from").value);
//		alert("fromNew"+fromNew);
  var fromNew1=fromNew.getFullYear()+"-"+zeroPadded(fromNew.getMonth()+1)+"-"+zeroPadded(fromNew.getDate())+" "+zeroPadded(fromNew.getHours())+":"+zeroPadded(fromNew.getMinutes())+":00";
  //  alert("fromNew1"+fromNew1);
  var toNew = new Date(document.getElementById("to").value);
//	alert("toNew"+toNew);
  var toNew1=toNew.getFullYear()+"-"+zeroPadded(toNew.getMonth()+1)+"-"+zeroPadded(toNew.getDate())+" "+zeroPadded(toNew.getHours())+":"+zeroPadded(toNew.getMinutes())+":00";
   //alert("toNew1"+toNew1);
 // d.setDate(d.getDate() + 1);

  // d.setTime(d.getTime()+ 1);


var od='<?php echo @$_REQUEST["od"]; ?>';
   var value= $('#pht').val();
   var a=0;
   var xhttp= new XMLHttpRequest();
   console.log(photo_id);
   console.log(fromNew);
    console.log(toNew);
  xhttp.onreadystatechange = function()
  {
    if(this.readyState == 4 && this.status == 200){

      a=parseInt(this.responseText);
  $("#BookingFound").val(a);
  if(a>0)
    {
     var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		$("#appointments_exist_error").html("Det er en annen avtale planlagt for den valgte fotografen mellom <br>"+fromNew1+" og "+toNew1+", Velg en annen dato og tid.");
		}
		else
		{
		$("#appointments_exist_error").html("There is another appoinment scheduled for the selected photographer <br> in between "+fromNew1+" and "+toNew1+", Kindly choose different Date & Time.");
		}
     $("#appointments_exist_error").show();
	 $("#BookingFound").val(a);
    return false;
    }
    else
    {
    //  alert("no appointment");
	$("#appointments_exist_error").hide();

    return false;
    }
    }
  };
  xhttp.open("GET","check_appointment.php?photographer_id="+photo_id+"&fromDate="+fromNew1+"&toDate="+toNew1+"&od="+od,true);
  xhttp.send();

  }


           </script>
			</div>

			      <div class="col-md-7" style="padding-top:10px;">



			<div class="breadcrumb1 hidden-xs hidden-sm">
		<a href="create_order.php?hs_id=<?php echo @$_REQUEST['hs_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&Photographer_id=<?php echo @$_REQUEST['Photographer_id']; ?>&u=1&od=<?php echo @$_REQUEST['od']; ?>" class="NonActiveBreadcrum" id="firstStep"><i class="fa fa-camera-retro" style="font-size:40px;"></i>
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_order" adr_trans="label_order">Order</span>
				<span class="breadcrumb__desc" id="label_fill_order" adr_trans="label_fill_order">Fill the order</span>
			</span>
		</a>

		<a href="#" id="secondStep" class="ActiveBreadcrum"><i class="fa fa-calendar" style="font-size:30px;color:#000;padding-top:10px;"></i>
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_appointment" adr_trans="label_appointment">Appointment</span>
				<span class="breadcrumb__desc" id="label_pick_appointment" adr_trans="label_pick_appointment">Pick appointment</span>

			</span>
		</a>
		<a href="#" id="thirdStep" class="NonActiveBreadcrum"><i class="fa fa-database" style="font-size:30px;padding-top:10px;"></i>
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_products" adr_trans="label_products">Products</span>
				<span class="breadcrumb__desc" id="label_select_products" adr_trans="label_select_products">Select Products</span>

			</span>
		</a>
		<a href="#" class="NonActiveBreadcrum"><i class="fa fa-file-text-o" style="font-size:30px;padding-top:10px;"></i>
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_summary" adr_trans="label_summary">Summary</span>
				<span class="breadcrumb__desc" id="label_order_status" adr_trans="label_order_status">Order Status</span>
			</span>
		</a>
	</div>


	<div class="breadcrumb1 hidden-md hidden-lg hidden-xl" style="height:50px;">
		<a href="create_order.php?hs_id=<?php echo @$_REQUEST['hs_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&Photographer_id=<?php echo @$_REQUEST['Photographer_id']; ?>&u=1&od=<?php echo @$_REQUEST['od']; ?>" id="firstStep">
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_order" adr_trans="label_order">Order</span>

			</span>
		</a>

		<a href="#" id="secondStep" class="btn ActionBtn-sm">
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_appointment" adr_trans="label_appointment">Appointment</span>


			</span>
		</a>
		<a href="#" id="thirdStep">
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_products" adr_trans="label_products">Products</span>


			</span>
		</a>
		<a href="#">
			<span class="breadcrumb__inner">
				<span class="breadcrumb__title" id="label_summary" adr_trans="label_summary">Summary</span>

			</span>
		</a><br />
	</div>


			<?php
			if(@$_REQUEST['od']!="")
			{
			$order_fetch1=mysqli_query($con,"select * from orders where id='$_REQUEST[od]'");
			$order_fetch=mysqli_fetch_array($order_fetch1);

			}

			?>
<?php if(@isset($_REQUEST["appdup"])) { ?>

                            <p class="text-error" align="center" style="font-style:italic;color:red">Sorry!. You have just missed.<br />Someone booked the selected slot of the photographer just few seconds ago.</p>

						<?php }  ?>
          <form action=""  method="post" enctype="multipart/form-data" onsubmit="return setSecondDate1()" id="appointmentForm" style="color: #000;background: #fff;padding:10px;border-radius:5px;">
		  <input type="hidden" id="BookingFound" value="0" />
           <input type="hidden" name="hs_id" value="<?php echo @$_REQUEST["hs_id"]; ?>"/>
		   <input type="hidden" name="pc_admin_id" value="<?php echo @$_REQUEST['pc_admin_id']; ?>" />
						<input type="hidden" name="Photographer_id" value="<?php echo @$_REQUEST['Photographer_id']; ?>" />
						<input type="hidden" name="od" value="<?php echo @$_REQUEST['od']; ?>" />
           <div class="col-md-12">

             <input id="address_same" value="1" onchange="setpropertyAddress()" <?php if(!isset($_REQUEST['edit'])){ echo "checked "; } ?>name="address_same" type="checkbox"  class="form-value">&nbsp;&nbsp; <span id="label_diff_property" adr_trans="label_diff_property">The property address is different from sellers address</span>

           </div>



          <div class="col-md-4">
              <p id="label_type_property" adr_trans="label_type_property">Type Of Property</p>
             <select name="property" id="TypeOfProperty" class="form-control form-value" required="" onchange="showHideFloors(this.value)" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
                         <option value="" id="label_select_property_type" adr_trans="label_select_property_type">Select a property type</option>

                              <option value="Apartment" id="label_appartment" <?php if(@$order_fetch['property_type']=="Apartment"){ echo "selected"; } ?> adr_trans="label_appartment">Apartment</option>
        					            <option value="Home" id="label_home" adr_trans="label_home" <?php if(@$order_fetch['property_type']=="Home"){ echo "selected"; } ?>>Home</option>
                              <option value="HolidayHome" id="label_holiday_home" adr_trans="label_holiday_home"<?php if(@$order_fetch['property_type']=="HolidayHome"){ echo "selected"; } ?>>Holiday Home</option>
                              <option value="EmptyLand" id="label_empty_land" adr_trans="label_empty_land"<?php if(@$order_fetch['property_type']=="EmptyLand"){ echo "selected"; } ?>>Empty Land</option>
                           </select>
             </div>
            <div class="col-md-4">
              <p id="label_floor_plans" adr_trans="label_floor_plans">No. Of Floor Plans</p>
              <input id="plan" name="plan" placeholder="Enter The Floor Number " type="number" min="0" max="999"  autocomplete="off" class="form-control form-value" required="" value="<?php echo @$order_fetch['number_of_floor_plans']; ?>" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
            </div>
            <div class="col-md-4">
              <p id="label_area" adr_trans="label_area">Area (Sq.Mt)</p>
              <input id="area" name="area" placeholder="Enter The Area" type="number"min="0" autocomplete="off" class="form-control form-value" required="" value="<?php echo @$order_fetch['area']; ?>" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
            </div>
            <div class="col-md-12" class="l">
                        <p id="label_property_address" adr_trans="label_property_address">Property Address</p>
                          <input id="property_address" name="property_address" placeholder="Enter The Address" type="text" autocomplete="off" class="form-control form-value" required="" value="<?php echo @$order_fetch['property_address']; ?>" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>

            </div>
<div class="col-md-6">
       <p id="label_property_city" adr_trans="label_property_city">Property City</p>
      <select id="property_city" onchange="get_states(this.value)"  name="property_city" class="form-control form-value" required="" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
      	<option value="">Select City</option>
                    <?php
              $city1=mysqli_query($con,"select cities from norway_states_cities order by cities asc");
              while($city=mysqli_fetch_array($city1))
              {
              ?>
              <option value="<?php echo $city['cities']; ?>" <?php if(@$order_fetch['property_city']==@$city['cities']){ echo "selected"; } ?> <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>><?php echo $city['cities']; ?></option>
              <?php } ?>
                    </select>
                    <span id="validation_message" style="display: none;color: red;position: absolute;top:0px;left:100px;"><span>
      </div>

      <div class="col-md-6">
       <p id="label_property_state" adr_trans="label_property_state">Property State</p>
      <select id="property_state"  name="property_state" class="form-control form-value"  required="" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>

              <option value="<?php if(isset($_SESSION['property_state'])) {echo $_SESSION['property_state'];}elseif(isset($order_fetch['property_state'])){echo @$order_fetch['property_state'];}?>"><?php if(isset($_SESSION['property_state'])) {echo $_SESSION['property_state'];}elseif(isset($order_fetch['property_state'])){echo @$order_fetch['property_state'];}?></option>
                    </select>
      </div>
     <div class="col-md-6">
                        <p id="label_property_zip" adr_trans="label_property_zip">Property Zip code</p>
                        <input id="property_zip" name="property_zip" placeholder="Zip code" type="number" autocomplete="off" class="form-control form-value"   required="" value="<?php echo @$order_fetch['property_zip']; ?>" readonly>
                    </div>


    <div class="col-md-6">
       <p id="label_property_country" adr_trans="label_property_country">Property Country</p>
      <select name="property_country" class="form-control form-value" required="" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
                    <option value="Norway">Norway</option>
                    <option value="US">US</option>
                    </select>
      </div>

          <div class="col-md-6">
                              <p id="label_property_phone" adr_trans="label_property_phone">Property Phone No.</p>
                              <input id="property_contact_mobile" name="property_contact_mobile" placeholder="Enter The mobile Number" type="tel" pattern="[0-9+.\(\)\-\s+]*" autocomplete="off" class="form-control form-value" value="<?php echo @$order_fetch['property_contact_mobile']; ?>" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
                          </div>

          <div class="col-md-6">
                              <p id="label_property_email" adr_trans="label_property_email">Property Email</p>
                              <input id="property_contact_email" name="property_contact_email" placeholder="Enter The email id" type="email" onblur="this.value=this.value.trim()"  autocomplete="off" class="form-control form-value"  value="<?php echo @$order_fetch['property_contact_email']; ?>" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
                              <br>
                          </div>







						  <div class="col-md-6">
						  <?php
			$photographersNameIs="";
			$photoCompanyNameIs="";
			 if(@$_REQUEST['Photographer_id'])
			 {
			 $photographers=mysqli_query($con,"select * from user_login where id='$_REQUEST[Photographer_id]'");
			 $photographers1=mysqli_fetch_array($photographers);
			 $photographersNameIs=$photographers1['first_name']." ".$photographers1['last_name'];
			 }


			 if(@$_REQUEST['pc_admin_id'])
			 {
			 $photoCompanies=mysqli_query($con,"select * from admin_users where id='$_REQUEST[pc_admin_id]'");
			 $photoCompanies1=mysqli_fetch_array($photoCompanies);
			 $photoCompanyNameIs=$photoCompanies1['organization_name'];
			 }


			?>
       <p id="label_photo_company" adr_trans="label_photo_company">Photo Company</p>



	   <input list="photocompanies" name="pht" class="form-control form-value" id="phtcompany"  value="<?php echo strtoupper(@$photoCompanyNameIs); ?>"  type="text"   placeholder="Select Photo company" autocomplete="off" readonly />
        <datalist id="photocompanies">
 	 <option value="" id="label_select_photo_company" adr_trans="label_select_photo_company">Select a Photo Company</option>

	   ><?php
	   $photoCompanyIs="";
	   if(@$_REQUEST['pc_admin_id'])
	   {
	   $photographers="select * from admin_users where id='$_REQUEST[pc_admin_id]'";

	   }
	   else
	   {
	   $photographers="select * from admin_users where type_of_user='PCAdmin' order by first_name";
	   }
         $Photographers_list=mysqli_query($con,$photographers);
         while($Photographers_list1=mysqli_fetch_assoc($Photographers_list))
        {?>
                    <option data-value="<?php echo $Photographers_list1["id"]; ?>" value="<?php echo strtoupper($Photographers_list1["organization_name"]);?>" <?php if($Photographers_list1["id"]==@$_REQUEST['$pc_admin_id'] || $Photographers_list1["id"]==@$order_fetch['$pc_admin_id']) { echo "selected"; } ?> <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>><?php echo strtoupper($Photographers_list1["organization_name"]);?></option>
                  <?php } ?>
                   
                  </datalist>



      <select name="product[]" id="products" class="form-control form-value" placeholder="Select Multiple Products"  multiple size=3 style="display:none;">

                    </select>
       </div>






            <div class="col-md-6">

       <p id="label_photographer" adr_trans="label_photographer">Photographer </p>
      <!-- <select name="pht_name" class="form-control form-value" required="" onchange="Get_Products(this.value);"> -->
        <input list="options" name="pht" class="form-control form-value" id="pht" type="text"  value="<?php echo @$photographersNameIs; ?>"  placeholder="Select Photographer" onclick="Get_Products()" onchange="Get_Products()"   autocomplete="off" required />
        <datalist id="options">
 	 <option value="" id="label_select_photographer" adr_trans="label_select_photographer">Select a Photographer</option>
       <?php
	   $photographers="";
	   if(@$_REQUEST['pc_admin_id'])
	   {
       $wherecod="";
       if($_SESSION['admin_loggedin_type']=="CSR")
       {
            $csr_id=$_SESSION['admin_loggedin_id'];
         $wherecod="and csr_id=$csr_id";
       }
	   $photographers="select * from user_login where type_of_user='Photographer' and pc_admin_id='$_REQUEST[pc_admin_id]' $wherecod order by first_name";
	   }
	   else
	   {

	     $photographers="select * from user_login where type_of_user='Photographer' and csr_id='$csr_id' order by first_name";
	   }
         $Photographers_list=mysqli_query($con,$photographers);
         while($Photographers_list1=mysqli_fetch_assoc($Photographers_list))
        {?>
                    <option data-value="<?php echo $Photographers_list1["id"]; ?>" value="<?php echo $Photographers_list1["first_name"]." ".$Photographers_list1["last_name"];?>" <?php if($Photographers_list1["id"]==@$_REQUEST['Photographer_id'] || $Photographers_list1["id"]==@$order_fetch['Photographer_id']) { echo "selected"; } ?>></option>
                  <?php } ?>
                   
                  </datalist>

                  </div>
                  <input id="rental_dormitory" value="1" name="rental_dormitory" type="checkbox" class=" form-value" <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>&nbsp;&nbsp; <span id="label_rental_apartment" adr_trans="label_rental_apartment">This Property has a Rental Apartment/Dormitory</span>

              <input type="hidden" name="pht_name" id="photo_id" value="<?php echo $_REQUEST["Photographer_id"]; ?>" />
     <?php
	 $from123="";
	 $to123="";
	 if(@$_REQUEST['od'])
	 {
     //echo "select * from appointments where order_id='$_REQUEST[od]'";
	 	$appointmentsAre=mysqli_query($con,"select * from appointments where order_id='$_REQUEST[od]'");
$appointmentsAre1=mysqli_fetch_array($appointmentsAre);

 @$from123=date("Y-m-d H:i",strtotime(@$appointmentsAre1['from_datetime']));
@$from123=preg_replace("/ /","T",$from123);
   @$to123=date("Y-m-d H:i",strtotime(@$appointmentsAre1['to_datetime']));
   @$to123=preg_replace("/ /","T",$to123);
   }
   if(isset($_SESSION['date'])!="")
   {
   $from123=$_SESSION['date']."T08:00:00";
    $to123=$_SESSION['date']."T08:00:00";
   }
   if((isset($_SESSION['fromDatetime'])!="") && (isset($_SESSION['toDatetime'])!=""))
   {
   $from123=$_SESSION['fromDatetime'];
   $to123=$_SESSION['toDatetime'];
   $from123Is=explode(" ",$from123);
   $to123Is=explode(" ",$to123);
    $from123=$from123Is[0];
   $to123=$to123Is[0];
   }

	  ?>

        <hr class="space s" />
             <div class="col-md-4">

                                <p id="label_appointment_from" adr_trans="label_appointment_from">From Date & Time  </p>
								<?php
								$editIs=0;
								if(@$_REQUEST['edit'])
								{
								$editIs=1;
								}

								 ?>
                                <input id="from" name="from" placeholder="select FromDate" type="datetime-local"  onchange="setSecondDate();" autocomplete="off" class="form-control form-value" <?php if(!isset($_SESSION['past'])) { ?> min="<?php echo date('Y-m-d')."T".date('H:m'); ?>" <?php } ?> minutestep="10" value="<?php echo $from123; ?>" <?php if(isset($_SESSION['date'])!='' || isset($_SESSION['fromDatetime'])!='' || @$_REQUEST['od']!=''||isset($_SESSION['admin_loggedin_type'])=='PCAdmin'||isset($_SESSION['admin_loggedin_type'])=='CSR') { echo "required";  } else { echo "readonly"; } ?>>
                            </div>

							<?php

							if(isset($_SESSION['date'])!="" || isset($_SESSION['fromDatetime'])!="")
							{
							?>
							<script>
							//alert("aaaaaaaaaa");
							//setSecondDate();
							</script>


							<?php } ?>
                            <?php
/*
														if(isset($_SESSION['time']))
														{
														  $dates=$_SESSION['date'].'T'.$_SESSION['time'];
															  echo '<script>$("#from").val("'.$dates.'")</script>';
															  echo '<script>$("#from").val("'.$date.'");</script>';
															echo '<script>$("#to").attr("min","'.$date.'");</script>';
															echo '<script>$("#due").attr("min","'.$date.'");</script>';
														}
														elseif(isset($_SESSION['date']))
														{
															$date=$_SESSION['date'].'T00:00';
															echo '<script>$("#from").val("'.$date.'");</script>';
															echo '<script>$("#to").attr("min","'.$date.'");</script>';
															echo '<script>$("#due").attr("min","'.$date.'");</script>';
														}
                            if(isset($_SESSION['photographer_id']))
														{
															$pht_id=$_SESSION['photographer_id'];
															$get_user_query=mysqli_query($con,"select * from user_login where id=$pht_id");
															$get_users=mysqli_fetch_assoc($get_user_query);
															$get_user=$get_users['first_name'];
															echo '<script>$("#pht").val("'.$get_user.'")</script>';
														}
														*/


                            ?>
            <div class="col-md-4">
                              <p id="label_appointment_to" adr_trans="label_appointment_to">To Date & Time</p>
                              <input id="to" name="to" placeholder="Select ToDate" type="datetime-local" autocomplete="off" class="form-control form-value" <?php if(!isset($_SESSION['past'])) { ?> min="<?php echo date('Y-m-d')."T".date('H:m'); ?>" <?php } ?> value="<?php echo @$to123; ?>" <?php if(isset($_SESSION['date'])!='' || isset($_SESSION['fromDatetime'])!='' || @$_REQUEST['od']!=''||isset($_SESSION['admin_loggedin_type'])=='PCAdmin'||isset($_SESSION['admin_loggedin_type'])=='CSR') { echo "required";  } else { echo "readonly"; } ?> >
                            </div>

            <div class="col-md-4">
                              <p id="label_due_date_time" adr_trans="label_due_date_time">Due Date & Time</p>
                              <input id="due" name="due" placeholder="Select DueDate" type="date" autocomplete="off" min="<?php if($to123!="") { echo date('Y-m-d',strtotime($to123));  } else { echo date('Y-m-d'); } ?>" value="<?php  if(@$_REQUEST['od']) { echo date("Y-m-d",strtotime(@$order_fetch['order_due_date'])); } ?>" class="form-control form-value" required <?php if(@$_REQUEST['edit']) { echo "readonly"; } ?>>
                            </div>



                <div class="col-md-12">
                                <p id="label_booking_notes" adr_trans="label_booking_notes">Booking Notes</p>
                     <textarea rows="5" cols="50" id="notes" name="notes" class="form-control form-value" required><?php echo @$order_fetch['booking_notes']; ?></textarea>

					 <input type="hidden" name="appointments_exist" id="appointments_exist" value="0" />
                </div>


             <div class="row">
                            <div class="col-md-12"><center><hr class="space s">
                              <div id="appointments_exist_error" class="text-danger" style="display:none"></div>
</center>

                     <?php 
                     $edit="";
                     if(isset($_REQUEST['edit']))
                     {
                     	$edit="&u=1";
                     }
                     ?>

                     <a  id="label_back" adr_trans="label_back" class="AnimationBtn CancelBtn-sm" href="create_order.php?hs_id=<?php echo @$_REQUEST['hs_id']; ?>&pc_admin_id=<?php echo @$_REQUEST['pc_admin_id']; ?>&Photographer_id=<?php echo @$_REQUEST['Photographer_id']; ?>&od=<?php echo @$_REQUEST['od'].$edit; ?>" style="float:left;margin-left:20px;"><i class="fa fa-chevron-circle-left"></i>Back</a>
					 <button class="AnimationBtn ActionBtn-sm" type="submit" name="save_appointment" style="float:right;margin-right:20px;" ><i class="fa fa-chevron-circle-right"></i><span id="label_next" adr_trans="label_next">Next</span></button>

             </div>

           </div>

            </form>
			</div>
			<div class="col-md-3">
<hr class="space s">
			<div id='calendar' style="display:block;"></div>

			</div>

            </div>
        </div>

<?php   if(isset($_SESSION['Photographer_id']))
{ ?>
<script>

  $(document).ready(function(){
    $('#pht').click();
	$('#pht').attr("readonly","readonly");
  })
</script>

<?php } ?>




<?php   if(!isset($_REQUEST['edit']))
{ ?>

<script>
$("#address_same").click();
showHideFloors($('#TypeOfProperty :selected').val());
</script>

<?php } ?>


		<?php include "footer.php";  ?>
